export const iOSDevices = [
    { identifier: "iPhone11,2", name: "iPhone XS", cpu: "Apple A12 Bionic (APL1W81) @ 2.50Ghz 6 Physical Core", gpu: "Apple G11P 4 Core", memory: 4.00 },
    { identifier: "iPhone11,6", name: "iPhone XS Max", cpu: "Apple A12 Bionic (APL1W81) @ 2.50Ghz 6 Physical Core", gpu: "Apple G11P 4 Core", memory: 4.00 },
    { identifier: "iPhone11,8", name: "iPhone XR", cpu: "Apple A12 Bionic (APL1W81) @ 2.50Ghz 6 Physical Core", gpu: "Apple G11P 4 Core", memory: 3.00 },
    { identifier: "iPhone12,1", name: "iPhone 11", cpu: "Apple A13 Bionic @ 2.66Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone12,3", name: "iPhone 11 Pro", cpu: "Apple A13 Bionic @ 2.66Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone12,5", name: "iPhone 11 Pro Max", cpu: "Apple A13 Bionic @ 2.66Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone12,8", name: "iPhone SE (2nd generation)", cpu: "Apple A13 Bionic @ 2.66Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPhone13,1", name: "iPhone 12 mini", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone13,2", name: "iPhone 12", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone13,3", name: "iPhone 12 Pro", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 6.00 },
    { identifier: "iPhone13,4", name: "iPhone 12 Pro Max", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 6.00 },
    { identifier: "iPhone14,2", name: "iPhone 13 Pro", cpu: "Apple A15 Bionic @ 3.20Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone14,3", name: "iPhone 13 Pro Max", cpu: "Apple A15 Bionic @ 3.20Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone14,4", name: "iPhone 13 mini", cpu: "Apple A15 Bionic @ 3.20Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone14,5", name: "iPhone 13", cpu: "Apple A15 Bionic @ 3.20Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone14,6", name: "iPhone SE (3nd generation)", cpu: "Apple A15 Bionic @ 3.20Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPhone14,7", name: "iPhone 14", cpu: "Apple A15 Bionic @ 3.20Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone14,8", name: "iPhone 14 Plus", cpu: "Apple A15 Bionic @ 3.20Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone15,2", name: "iPhone 14 Pro", cpu: "Apple A16 Bionic @ 3.50Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone15,3", name: "iPhone 14 Pro Max", cpu: "Apple A16 Bionic @ 3.50Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone15,4", name: "iPhone 15", cpu: "Apple A16 Bionic @ 3.50Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone15,5", name: "iPhone 15 Plus", cpu: "Apple A16 Bionic @ 3.50Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 6.00 },
    { identifier: "iPhone16,1", name: "iPhone 15 Pro", cpu: "Apple A17 Pro @ 3.80Ghz 6 Physical Core", gpu: "Apple GPU 6 Core", memory: 8.00 },
    { identifier: "iPhone16,2", name: "iPhone 15 Pro Max", cpu: "Apple A17 Pro @ 3.80Ghz 6 Physical Core", gpu: "Apple GPU 6 Core", memory: 8.00 },
    { identifier: "iPhone17,3", name: "iPhone 16", cpu: "Apple A18 @ 4.04Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 8.00 },
    { identifier: "iPhone17.4", name: "iPhone 16 Plus", cpu: "Apple A18 @ 4.04Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 8.00 },
    { identifier: "iPhone17,1", name: "iPhone 16 Pro", cpu: "Apple A18 Pro @ 4.04Ghz 6 Physical Core", gpu: "Apple GPU 6 Core", memory: 8.00 },
    { identifier: "iPhone17,2", name: "iPhone 16 Pro Max", cpu: "Apple A18 Pro @ 4.04Ghz 6 Physical Core", gpu: "Apple GPU 6 Core", memory: 8.00 },

    { identifier: "iPad7,3", name: "iPad Pro (10.5-inch) (Wi-Fi)", cpu: "Apple A10X Fusion @ 2.30Ghz 6 Physical Core", gpu: "PowerVR Series 12 Core", memory: 4.00 },
    { identifier: "iPad7,4", name: "iPad Pro (10.5-inch) (Wi-Fi + Cellular)", cpu: "Apple A10X Fusion @ 2.30Ghz 6 Physical Core", gpu: "PowerVR Series 12 Core", memory: 4.00 },
    { identifier: "iPad7,1", name: "iPad Pro (12.9-inch) (2nd generation) (Wi-Fi)", cpu: "Apple A10X Fusion @ 2.30Ghz 6 Physical Core", gpu: "PowerVR Series 12 Core", memory: 4.00 },
    { identifier: "iPad7,2", name: "iPad Pro (12.9-inch) (2nd generation) (Wi-Fi + Cellular)", cpu: "Apple A10X Fusion @ 2.30Ghz 6 Physical Core", gpu: "PowerVR Series 12 Core", memory: 4.00 },
    { identifier: "iPad7,5", name: "iPad Pro (6th generation) (Wi-Fi)", cpu: "Apple A10 Fusion @ 2.30Ghz 4 Physical Core", gpu: "PowerVR Series 7XT Plus 6 Core", memory: 2.00 },
    { identifier: "iPad7,6", name: "iPad Pro (6th generation) (Wi-Fi + Cellular)", cpu: "Apple A10 Fusion @ 2.30Ghz 4 Physical Core", gpu: "PowerVR Series 7XT Plus 6 Core", memory: 2.00 },
    { identifier: "iPad8,1", name: "iPad Pro (11-inch) (1st generation) (Wi-Fi)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 4.00 },
    { identifier: "iPad8,2", name: "iPad Pro (11-inch) (1st generation) (Wi-Fi)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 6.00 },
    { identifier: "iPad8,3", name: "iPad Pro (11-inch) (1st generation) (Wi-Fi + Cellular)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 4.00 },
    { identifier: "iPad8,4", name: "iPad Pro (11-inch) (1st generation) (Wi-Fi + Cellular)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 6.00 },
    { identifier: "iPad8,5", name: "iPad Pro (12.9-inch) (3rd generation) (Wi-Fi)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 4.00 },
    { identifier: "iPad8,6", name: "iPad Pro (12.9-inch) (3rd generation) (Wi-Fi)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 6.00 },
    { identifier: "iPad8,7", name: "iPad Pro (12.9-inch) (3rd generation) (Wi-Fi + Cellular)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 4.00 },
    { identifier: "iPad8,8", name: "iPad Pro (12.9-inch) (3rd generation) (Wi-Fi + Cellular)", cpu: "Apple A12X Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 7 Core", memory: 6.00 },
    { identifier: "iPad11,3", name: "iPad Air (3rd generation) (Wi-Fi)", cpu: "Apple A12 Bionic @ 2.50Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad11,4", name: "iPad Air (3rd generation) (Wi-Fi + Cellular)", cpu: "Apple A12 Bionic @ 2.50Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad11,1", name: "iPad mini (5th generation) (Wi-Fi)", cpu: "Apple A12 Bionic @ 2.50Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad11,2", name: "iPad mini (5th generation) (Wi-Fi + Cellular)", cpu: "Apple A12 Bionic @ 2.50Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad7,11", name: "iPad (7th generation) (Wi-Fi)", cpu: "Apple A10 Fusion @ 2.30Ghz 4 Physical Core", gpu: "PowerVR Series 7XT Plus 6 Core", memory: 3.00 },
    { identifier: "iPad7,12", name: "iPad (7th generation) (Wi-Fi + Cellular)", cpu: "Apple A10 Fusion @ 2.30Ghz 4 Physical Core", gpu: "PowerVR Series 7XT Plus 6 Core", memory: 3.00 },
    { identifier: "iPad8,9", name: "iPad Pro (11-inch) (2nd generation) (Wi-Fi)", cpu: "Apple A12Z Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 6.00 },
    { identifier: "iPad8,10", name: "iPad Pro (11-inch) (2nd generation) (Wi-Fi + Cellular)", cpu: "Apple A12Z Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 6.00 },
    { identifier: "iPad8,11", name: "iPad Pro (12.9-inch) (4th generation) (Wi-Fi)", cpu: "Apple A12Z Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 6.00 },
    { identifier: "iPad8,12", name: "iPad Pro (12.9-inch) (4th generation) (Wi-Fi + Cellular)", cpu: "Apple A12Z Bionic @ 2.50Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 6.00 },
    { identifier: "iPad11,6", name: "iPad (8th generation) (Wi-Fi)", cpu: "Apple A12 Bionic @ 2.50Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad11,7", name: "iPad (8th generation) (Wi-Fi + Cellular)", cpu: "Apple A12 Bionic @ 2.50Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad13,1", name: "iPad Air (4th generation) (Wi-Fi)", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPad13,2", name: "iPad Air (4th generation) (Wi-Fi + Cellular)", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPad13,4", name: "iPad Pro (11-inch) (3rd generation) (Wi-Fi)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 8.00 },
    { identifier: "iPad13,5", name: "iPad Pro (11-inch) (3rd generation) (Wi-Fi)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 16.00 },
    { identifier: "iPad13,6", name: "iPad Pro (11-inch) (3rd generation) (Wi-Fi + Cellular)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 8.00 },
    { identifier: "iPad13,7", name: "iPad Pro (11-inch) (3rd generation) (Wi-Fi + Cellular)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 16.00 },
    { identifier: "iPad13,8", name: "iPad Pro (12.9-inch) (5th generation) (Wi-Fi)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 8.00 },
    { identifier: "iPad13,9", name: "iPad Pro (12.9-inch) (5th generation) (Wi-Fi)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 16.00 },
    { identifier: "iPad13,10", name: "iPad Pro (12.9-inch) (5th generation) (Wi-Fi + Cellular)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 8.00 },
    { identifier: "iPad13,11", name: "iPad Pro (12.9-inch) (5th generation) (Wi-Fi + Cellular)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 16.00 },
    { identifier: "iPad12,1", name: "iPad (9th generation) (Wi-Fi)", cpu: "Apple A13 Bionic @ 2.66Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad12,2", name: "iPad (9th generation) (Wi-Fi + Cellular)", cpu: "Apple A13 Bionic @ 2.66Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 3.00 },
    { identifier: "iPad14,1", name: "iPad mini (6th generation) (Wi-Fi)", cpu: "Apple A15 Bionic @ 2.90Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 4.00 },
    { identifier: "iPad14,2", name: "iPad mini (6th generation) (Wi-Fi + Cellular)", cpu: "Apple A15 Bionic @ 2.90Ghz 6 Physical Core", gpu: "Apple GPU 5 Core", memory: 4.00 },
    { identifier: "iPad13,16", name: "iPad Air (5th generation) (Wi-Fi)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 8.00 },
    { identifier: "iPad13,17", name: "iPad Air (5th generation) (Wi-Fi + Cellular)", cpu: "Apple M1 @ 3.20Ghz 8 Physical Core", gpu: "Apple GPU 8 Core", memory: 8.00 },
    { identifier: "iPad13,18", name: "iPad (10th generation) (Wi-Fi)", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPad13,19", name: "iPad (10th generation) (Wi-Fi + Cellular)", cpu: "Apple A14 Bionic @ 3.00Ghz 6 Physical Core", gpu: "Apple GPU 4 Core", memory: 4.00 },
    { identifier: "iPad14,3", name: "iPad Pro (11-inch) (4th generation) (Wi-Fi)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
    { identifier: "iPad14,4", name: "iPad Pro (11-inch) (4th generation) (Wi-Fi + Cellular)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
    { identifier: "iPad14,5", name: "iPad Pro (12.9-inch) (6th generation) (Wi-Fi)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
    { identifier: "iPad14,6", name: "iPad Pro (12.9-inch) (6th generation) (Wi-Fi + Cellular)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
    { identifier: "iPad14,8", name: "iPad Air 11-inch (M2) (Wi-Fi)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 9 Core", memory: 8.00 },
    { identifier: "iPad14,9", name: "iPad Air 11-inch (M2) (Wi-Fi + Cellular)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 9 Core", memory: 8.00 },
    { identifier: "iPad14,10", name: "iPad Air 13-inch (M2) (Wi-Fi)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 9 Core", memory: 8.00 },
    { identifier: "iPad14,11", name: "iPad Air 13-inch (M2) (Wi-Fi + Cellular)", cpu: "Apple M2 @ 3.50Ghz 8 Physical Core", gpu: "Apple GPU 9 Core", memory: 8.00 },
    { identifier: "iPad16,3", name: "iPad Pro 11-inch (M4) (Wi-Fi)", cpu: "Apple M4 @ 4.40Ghz 9 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Number of CPU Cores: 9 (256 or 512 GB storage) 10 (1 or 2 TB storage) Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
    { identifier: "iPad16,4", name: "iPad Pro 11-inch (M4) (Wi-Fi + Cellular)", cpu: "Apple M4 @ 4.40Ghz 9 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Number of CPU Cores: 9 (256 or 512 GB storage) 10 (1 or 2 TB storage) Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
    { identifier: "iPad16,5", name: "iPad Pro 13-inch (M4) (Wi-Fi)", cpu: "Apple M4 @ 4.40Ghz 9 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Number of CPU Cores: 9 (256 or 512 GB storage) 10 (1 or 2 TB storage) Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
    { identifier: "iPad16,6", name: "iPad Pro 13-inch (M4) (Wi-Fi + Cellular)", cpu: "Apple M4 @ 4.40Ghz 9 Physical Core", gpu: "Apple GPU 10 Core", memory: 8.00 }, // Number of CPU Cores: 9 (256 or 512 GB storage) 10 (1 or 2 TB storage) Memory: 8 GB (128, 256, or 512 GB storage) 16 GB (1 or 2 TB storage)
];
